# Generated by Django 5.2.8 on 2025-11-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='アドオン名')),
                ('slug', models.SlugField(unique=True, verbose_name='URL用の名前')),
                ('description', models.TextField(verbose_name='説明')),
                ('long_description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('addon_type', models.CharField(choices=[('behavior', 'Behavior Pack'), ('resource', 'Resource Pack'), ('skin', 'Skin Pack'), ('world', 'World Template'), ('other', 'Other')], default='behavior', max_length=20, verbose_name='種類')),
                ('version', models.CharField(max_length=20, verbose_name='バージョン')),
                ('author', models.CharField(max_length=100, verbose_name='作成者')),
                ('minecraft_version', models.CharField(default='1.21+', max_length=50, verbose_name='対応 Minecraft バージョン')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='addons/thumbnails/', verbose_name='サムネイル')),
                ('download_file', models.FileField(upload_to='addons/files/', verbose_name='ダウンロードファイル')),
                ('downloads', models.IntegerField(default=0, verbose_name='ダウンロード数')),
                ('likes', models.IntegerField(default=0, verbose_name='いいね数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('published', models.BooleanField(default=True, verbose_name='公開')),
            ],
            options={
                'verbose_name': 'アドオン',
                'verbose_name_plural': 'アドオン',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddonScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='addons/screenshots/', verbose_name='スクリーンショット')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='キャプション')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='project.addon')),
            ],
            options={
                'verbose_name': 'スクリーンショット',
                'verbose_name_plural': 'スクリーンショット',
                'ordering': ['order'],
            },
        ),
    ]
