# Generated by Django 5.2.8 on 2025-11-12 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_banrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='利用規約', max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('active', models.BooleanField(default=True, help_text='有効なページが複数ある場合は最新の active=True を表示します', verbose_name='公開中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '固定ページ（利用規約等）',
                'verbose_name_plural': '固定ページ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='addon',
            name='addon_type',
            field=models.CharField(choices=[('behavior', 'ビヘイビアパック'), ('resource', 'リソースパック'), ('skin', 'スキンパック'), ('world', 'ワールドテンプレート'), ('other', 'その他')], default='behavior', max_length=20, verbose_name='種類'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='件名')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('handled', models.BooleanField(default=False, verbose_name='対応済み')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'お問い合わせメッセージ',
                'verbose_name_plural': 'お問い合わせメッセージ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='通報対象のURL')),
                ('description', models.TextField(verbose_name='通報内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='project.addon')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通報',
                'verbose_name_plural': '通報',
                'ordering': ['-created_at'],
            },
        ),
    ]
