# Generated by Django 5.2.8 on 2025-11-12 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_termspage_alter_addon_addon_type_contactmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='件名')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('replied_at', models.DateTimeField(auto_now_add=True, verbose_name='返信日時')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.contactmessage')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '問い合わせ返信',
                'verbose_name_plural': '問い合わせ返信',
                'ordering': ['-replied_at'],
            },
        ),
    ]
