# Generated by Django 5.2.8 on 2025-11-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_contactreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='termspage',
            options={'ordering': ['-created_at'], 'verbose_name': '利用規約設定', 'verbose_name_plural': '利用規約設定'},
        ),
    ]
