# Generated by Django 5.2.8 on 2025-11-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki/', verbose_name='サムネイル画像'),
        ),
    ]
